name: Build & Deploy

on:
  push:
    branches: 
      - main
      - dev       
  pull_request:
    branches: 
      - main
      - dev
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with: 
          Node-version: 16
     
      - name: Install dependencies
        run: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build
         
      - name: Upload production-ready build files 
        uses: actions/upload-artifect@v2
        with: 
          name: production-files 
          path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == ’refs/heads/develop’
    steps:
      - name: Download artifect
        uses: action/download-artifact@v2
        with: 
          name: production-files
          path: ./build
	
      - name: Deploy to GitHub pages
        uses: peaceiris/action-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build
